apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-define-serviceaccount-policy
  annotations:
    policies.kyverno.io/title: Enforce Service Account is Defined
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: serviceaccount-name
      match:
        any:
          - resources:
              kinds:
                - helm.toolkit.fluxcd.io/v2beta1/HelmRelease
                - kustomize.toolkit.fluxcd.io/v1beta2/Kustomization
      exclude:
        any:
          - resources:
              namespaces:
                - flux-system
      validate:
        message: "serviceAccountName must be specified"
        pattern:
          spec:
            serviceAccountName: "?*"
