# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     toolkit.fluxcd.io/tenant: dev-team
#   name: apps
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   labels:
#     toolkit.fluxcd.io/tenant: dev-team
#   name: dev-team
#   namespace: prospeccao-stage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev-team
  name: dev-team-reconciler
  namespace: prospeccao-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: project-owner
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: gf-nupros-ocp4bm2
- kind: ServiceAccount
  name: cicd
  namespace: prospeccao-stage
