---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gatekeeper.yaml
  #{disable} - https://raw.githubusercontent.com/kyverno/kyverno/v1.4.3/definitions/release/install.yaml
