apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: policy-engine
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/policy-engine
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: policies
  namespace: flux-system
spec:
  dependsOn:
    - name: policy-engine
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/policies
  prune: true
  validation: client
