apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  dependsOn:
    - name: policies
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: platform-team
  path: ./tenants/staging
  prune: true
  validation: client
