---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: prospeccao-stage
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-ocp-gitops2022
  path: ./infra/flux-monitoring
  prune: true
  validation: client
